services:
  - type: web
    name: course-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: course-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_CHAT_ID
        sync: false
      - key: CHANNEL_INVITE_LINK
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_BOT_USERNAME
        sync: false
      - key: NEXT_PUBLIC_CHANNEL_ID
        sync: false
      - key: NEXT_PUBLIC_CHANNEL_INVITE_LINK
        sync: false
      - key: NEXT_PUBLIC_ADMIN_USER_ID
        sync: false

databases:
  - name: course-management-db
    plan: free
